#!/bin/bash

echo "🔍 Verificando instalación de la extensión..."

# Desinstalar versión anterior si existe
code --uninstall-extension local.autonomous-mcp-helper 2>/dev/null || true

echo "📦 Instalando nueva versión..."
code --install-extension autonomous-mcp-helper-0.0.9.vsix

echo "🎯 Instrucciones para verificar el panel:"
echo ""
echo "1. Abre VS Code"
echo "2. Ve a la barra lateral izquierda"
echo "3. Busca el ícono 'Autonomous Copilot' (debería aparecer con un ícono verde)"
echo "4. Haz clic en él para abrir las vistas:"
echo "   - 📊 Dashboard: Métricas y control del motor"
echo "   - 📝 Historial: Actividades registradas"
echo "   - ⚙️ Configuración: Ajustes avanzados"
echo "5. Si no aparece, ve a Ver > Comando > 'Developer: Reload Window'"
echo "6. Para ver logs: Ver > Output > selecciona 'Log (Extension Host)'"
echo ""
echo "🤖 NUEVA FUNCIONALIDAD v0.0.9: CHAT PARTICIPANT!"
echo "1. Abre el Chat de Copilot (Ctrl+Alt+I o desde la barra lateral)"
echo "2. Escribe: @autonomousai analiza mi código"
echo "3. ¡El chat responderá automáticamente usando OpenAI!"
echo ""
echo "📋 Comandos disponibles del Chat Participant:"
echo "- @autonomousai /analyze - Analiza código y sugiere mejoras"
echo "- @autonomousai /fix - Encuentra y corrige errores"
echo "- @autonomousai /optimize - Optimiza el código"
echo "- @autonomousai /explain - Explica cómo funciona el código"
echo "- @autonomousai [pregunta libre] - Respuesta general"
echo ""
echo "✨ Funcionalidades v0.0.9:"
echo "- Chat Participant @autonomousai integrado con Copilot"
echo "- Respuestas automáticas usando tu servidor MCP local"
echo "- Análisis de contexto automático (archivo activo, errores, selección)"
echo "- Historial de interacciones en el dashboard"
echo "- 4 comandos especializados (/analyze, /fix, /optimize, /explain)"
echo ""
echo "🐛 Para debugear:"
echo "- Abre DevTools: Ayuda > Toggle Developer Tools"
echo "- Ve a Console para ver los logs que agregamos"
echo ""
echo "✅ Instalación completada - Recarga VS Code manualmente"
